### ISSUE TITLE
The modified version of retrieveNameFromID and retrieveNamesFromJSON is wrong

### ISSUE THREAD

**Issue by raymondlui719** [raymondlui719/teamform-seed#3]
The reason is that it is not necessary to push an firebaseObject each time to $scope.users
If you do so, you cannot simply retrieve the name of the users by calling $scope.users[tmpIdx].name, this is going to return "undefined"(except for id with numbers only, i dunno why tho).

So I suggest you that in COMP2222 event page, add a name and userid property inside $id and revert the two methods into mine so that it will work properly again. Otherwise it will only work for integer $ids.

**Comment by cflamad** [comment]
I just figured out that it returns undefined because it did not create an new record on "user" when an new user login to the system. I will fix it later.

The reason i do not add name and userid property in every member is that there would be many duplicated data if I do in this way. For example, if a user join two teams in two events, then we have to save the user name and user ID in two events. At the same time, nesting the data is difficult to extend.

**Comment by raymondlui719** [comment]
I get it now. I will change the login flow and add user info (e.g. name) in the path /user/ + id.

**Comment by raymondlui719** [comment]
Also, the userid is not useful now, I will delete this also.
