### ISSUE TITLE
problem of getting the length of the firebase array

### ISSUE THREAD

**Issue by ykcsteven** [raymondlui719/teamform-seed#34]
In the abilitytest.js, I get an array of the quiz by using this line:
$scope.quiz = []
$scope.quiz = $firebaseArray(firebase.database().ref("quiz/java"));
it can help me to get the array and there is no problem.
However, if I create a variable like:
var aaa = $scope.quiz.length
this variable will be 0
But, if I directly show the length in the html like:
{{quiz.length}}
it can output the length of the array

**Comment by cflamad** [comment]
It may be caused due to the asynchronous processing of firebase. When you run $scope.quiz = $firebaseArray(firebase.database().ref("quiz/java")); , you send a request to get the data from firebase. Then the program immediately go to the next line without waiting the arrival of the data. Therefore you can length 0
