### ISSUE TITLE
Bug found in team.html and team.js

### ISSUE THREAD

**Issue by tsecheukyan1** [raymondlui719/teamform-seed#8]
There is bug that users can't form new team at an event, pressed add button but nothing happens.
I bet there is something wrong in the savefunc inside team.js

**Comment by raymondlui719** [comment]
I finally realize that the problem is actually:
When I try to add a team in team.html, the saveFunc inside team.js try to cancel all the member's requests 
`$.each($scope.param.teamMembers, function(i, obj) {
	var rec = $scope.member.$getRecord(obj);
	rec.selection = [];
	rec.inTeam = teamID;
	$scope.member.$save(rec);
});`
But the member record actually doesn't exist, so it returns an error here.
For the case that I can add a team as discussed in group chat is that I already save my record in member.html.
I think we can solve this by the following:
Tell the user to register in event from the member page first in order to add a team or request to join a team;
If the event doesn't exist in the first place, when the user creates it, it should automatically add a member entry for the event admin.

**Comment by tsecheukyan1** [comment]
Oh I get it, so will u fix it, or should I do it?

**Comment by raymondlui719** [comment]
I will fix it.

**Comment by tsecheukyan1** [comment]
Maybe we pop an error message for the users who didn't join the event before adding team in the team page.

**Comment by cflamad** [comment]
Can we modify the code such that if we cannot find the user in member, we add an new record to member automatically? Joining an event as a team leader should be considered as a legal action. Joining the event as member then as a team leader may be annoying.

**Comment by raymondlui719** [comment]
Updated and I am going to commit this after the testing passes.
